# Generated by Django 2.0.2 on 2018-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDestinoViagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DestinoDeViagens',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False, verbose_name='Registro N')),
                ('locaisDeDestinoDeViagens', models.CharField(max_length=50, verbose_name='Locais de Destino de Viagens')),
                ('orgaosDeDestinoDeViagens', models.CharField(max_length=50, verbose_name='Òrgãos de Destino de Viagens')),
                ('FinalidadeDaViagem', models.CharField(max_length=50, verbose_name='Finalidade da Viagem')),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaDoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NivelDaDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrigensDeViagens',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('locaisDeOrigemDeViagens', models.CharField(max_length=50)),
                ('orgaosDeOrigemDeViagens', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiglaDaParcelaDeDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla da Parcela de Diária')),
                ('status', models.BooleanField()),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição da Parcela de Diária')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeTransporte',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDeTransport', models.TextField(verbose_name='Tipo de Transporte')),
                ('natureza', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeDespesasEmViagens',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Registro N')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição da Dspesa')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
