# Generated by Django 2.1.2 on 2018-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='numero',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
