# Generated by Django 2.1.2 on 2018-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_rotariano'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotariano',
            name='cpf',
            field=models.CharField(default=11111111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='distrito',
            field=models.CharField(default=0.0005558362809499747, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='endereco',
            field=models.CharField(default=111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='estadocivil',
            field=models.CharField(default=1111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='identidade',
            field=models.CharField(default=1111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='presidente',
            field=models.CharField(default=1111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='profissao',
            field=models.CharField(default=111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotariano',
            name='sede',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
