# Generated by Django 2.1 on 2018-09-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeAluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRequerimento', models.DateField(blank=True, verbose_name='Data de Falecimento')),
                ('dataLocacao', models.DateField(blank=True, verbose_name='Data de Sepultamento')),
                ('cadeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Cadeira', verbose_name='Codigo Cadeira')),
                ('comodante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comodante2comodante', to='pessoa.Pessoa')),
                ('parentesco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Parentesco', verbose_name='Grau de Parentesco')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario2usuario', to='pessoa.Pessoa')),
            ],
        ),
    ]
