# Generated by Django 2.1.2 on 2018-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_cadastrodealuguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrodealuguel',
            name='dataLocacao',
            field=models.DateField(blank=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='cadastrodealuguel',
            name='dataRequerimento',
            field=models.DateField(blank=True, verbose_name='Data de Requerimento'),
        ),
    ]
