# Generated by Django 2.0.3 on 2018-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20181107_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrodealuguel',
            name='dataLocacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='cadastrodealuguel',
            name='dataRequerimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Requerimento'),
        ),
    ]
