# Generated by Django 2.0.3 on 2018-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20181110_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataEmprestimo',
            field=models.DateField(blank=True, null=True, verbose_name='Emprestimo'),
        ),
    ]
