# Generated by Django 2.0.3 on 2018-11-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_auto_20181110_1324'),
        ('pessoa', '0005_cadastrodealuguel_dataemprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='andador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Andador', verbose_name='Codigo Andador'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='cadeiraDeBanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.CadeiraDeBanho', verbose_name='Codigo Cadeira de Banho'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='muleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Muleta', verbose_name='Codigo Muleta'),
        ),
    ]
