# Generated by Django 2.0.3 on 2018-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20181110_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrodealuguel',
            name='dataEmprestimo',
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataEmprestimoAndador',
            field=models.DateField(blank=True, null=True, verbose_name='Emprestimo Andador'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataEmprestimoCadeira',
            field=models.DateField(blank=True, null=True, verbose_name='Emprestimo Cadeira'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataEmprestimoCadeiraDeBanho',
            field=models.DateField(blank=True, null=True, verbose_name='Emprestimo Cadeira de Banho'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataEmprestimoMuleta',
            field=models.DateField(blank=True, null=True, verbose_name='Emprestimo Muleta'),
        ),
    ]
