# Generated by Django 2.0.3 on 2018-11-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20181110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataDevolucaoAndador',
            field=models.DateField(blank=True, null=True, verbose_name='Devolucao Andador'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataDevolucaoCadeira',
            field=models.DateField(blank=True, null=True, verbose_name='Devolucao Cadeira'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataDevolucaoCadeiraDeBanho',
            field=models.DateField(blank=True, null=True, verbose_name='Devolucao Cadeira de Banho'),
        ),
        migrations.AddField(
            model_name='cadastrodealuguel',
            name='dataDevolucaoMuleta',
            field=models.DateField(blank=True, null=True, verbose_name='Devolucao Muleta'),
        ),
    ]
