# Generated by Django 2.0.2 on 2018-05-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidor', '0001_initial'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificaRquisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPortaria', models.DateField(verbose_name='Data da Portaria')),
                ('cargodoservidor', models.CharField(max_length=100, verbose_name='Cargo do Servidor')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidades')),
                ('exercicio', models.CharField(max_length=100, verbose_name='exercicio')),
                ('portariaautprizativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.PortariasAutorizativa')),
            ],
        ),
        migrations.CreateModel(
            name='Rcv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(default='2011', max_length=4)),
                ('dataSolicitacao', models.DateField(verbose_name='Data Solicitação')),
                ('periodoInicio', models.DateTimeField(verbose_name='Início')),
                ('periodoTermino', models.DateTimeField(verbose_name='Término')),
                ('objetivo', models.TextField(verbose_name='Objetivo da Viagem')),
                ('atividades', models.TextField(verbose_name='Atividades Realizadas')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Cargo')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Servidor')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.UnidadesAdministrativa', verbose_name='Unidade Administrativa')),
            ],
        ),
        migrations.CreateModel(
            name='Sdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(default='2011', max_length=4)),
                ('dataSolicitacao', models.DateField(verbose_name='Data Solicitação')),
                ('periodoInicio', models.DateTimeField(verbose_name='Início')),
                ('periodoTermino', models.DateTimeField(verbose_name='Término')),
                ('diariaValorSolicitado', models.PositiveIntegerField(verbose_name='Diária Valor Solicitado')),
                ('diariaValorAprovado', models.PositiveIntegerField(verbose_name='Diária Valor Aprovado')),
                ('alimentacaoValorSolicitado', models.PositiveIntegerField(verbose_name='Alimentação Valor Solicitado')),
                ('alimentacaoValorAprovado', models.PositiveIntegerField(verbose_name='Alimentacao Valor Aprovado')),
                ('transporteValorSolicitado', models.PositiveIntegerField(verbose_name='Transporte Urbano Valor Solicitado')),
                ('transporteValorAprovado', models.PositiveIntegerField(verbose_name='Transporte Valor Aprovado')),
                ('passagemValorSolicitado', models.PositiveIntegerField(verbose_name='Passagem Valor Solicitado')),
                ('passagemValorAprovado', models.PositiveIntegerField(verbose_name='Passagem Valor Aprovado')),
                ('observacoes', models.TextField(verbose_name='Observação')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Cargo')),
                ('localidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.Localidade')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Servidor')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.UnidadesAdministrativa', verbose_name='Unidade Administrativa')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
