# Generated by Django 2.0.2 on 2018-05-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.IntegerField()),
                ('denominacao', models.CharField(max_length=200)),
                ('codigoCargo', models.CharField(max_length=20, verbose_name='Código do Cargo')),
                ('simboloDeVencimento', models.CharField(max_length=20, verbose_name='Simbolo de Vencimento')),
                ('recrutamento', models.CharField(max_length=100)),
                ('leiDeCriacao', models.CharField(max_length=100, verbose_name='Lei de Criação')),
                ('poderDeLotacao', models.CharField(max_length=200, verbose_name='Poder de lotação')),
                ('escolaridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Escolaridade')),
                ('naurezaDoCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.NaturezaDoCargo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfisDeDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.IntegerField(verbose_name='Registro N')),
                ('tabela', models.CharField(max_length=100)),
                ('dataDaTabela', models.DateField(auto_now=True, verbose_name='Data da Tabela')),
                ('cargo', models.CharField(max_length=100)),
                ('escolaridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.Escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='PortariasAutorizativa',
            fields=[
                ('registro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Registro N')),
                ('portaria', models.CharField(max_length=10)),
                ('dataExpedicao', models.DateField(auto_now_add=True, verbose_name='Data da Expedição')),
                ('orgaoEmissor', models.CharField(max_length=100)),
                ('dataDoInicioDaViagem', models.DateField(verbose_name='Data do Início da Viagem')),
                ('horaDoInicioDaViagem', models.TimeField(verbose_name='Hora do Início da Viagem')),
                ('dataDoTerminioDaViagem', models.DateField(verbose_name='Data do Términio da viagem')),
                ('horaDoTerminioDaViagem', models.TimeField(verbose_name='Hora do Términio da Viagem')),
                ('missao', models.TextField(verbose_name='Missão')),
                ('cargoDoEmissor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Cargo')),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.DestinoDeViagens')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesAdministrativa',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('siglaUnidadeAdministrativa', models.CharField(max_length=10, verbose_name='Sigla da Unidade Administrativa')),
                ('unidadeAdministrativa', models.TextField(max_length=100, verbose_name='Unidade Administrativa')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('expedienteChegada', models.TimeField(verbose_name='Das')),
                ('expedienteSaidaAlmoco', models.TimeField(verbose_name='às')),
                ('expedienteEntradaAlmoco', models.TimeField(verbose_name='Das')),
                ('expedienteSaida', models.TimeField(verbose_name='às')),
                ('cep', models.CharField(max_length=15, verbose_name='Cep')),
                ('municipios', models.CharField(max_length=70, verbose_name='Município')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endereco.Estado')),
            ],
            options={
                'get_latest_by': 'siglaUnidadeAdministrativa',
            },
        ),
        migrations.AddField(
            model_name='portariasautorizativa',
            name='nomeServidorEmissor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidor.Servidor', verbose_name='Nome do Servidor Emissor'),
        ),
        migrations.AddField(
            model_name='portariasautorizativa',
            name='orgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.OrigensDeViagens'),
        ),
    ]
